name: API

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Run tests
        run: go test -v ./...

      - name: Build Go app
        run: go build -v

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}_${{ github.ref_name }}:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
        env:
          DOCKER_BUILDKIT: 1
